spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geo-postgres
    username: username
    password: mysecretpassword
  docker:
    compose:
      file: "./docker-compose.yml"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

    hibernate:
      ddl-auto: create-drop
